export const symbols = [
  { value: "ā", needsFont: false },
  { value: "á", needsFont: false },
  { value: "ǎ", needsFont: false },
  { value: "à", needsFont: false },
  { value: "ē", needsFont: false },
  { value: "é", needsFont: false },
  { value: "ě", needsFont: false },
  { value: "è", needsFont: false },
  { value: "ī", needsFont: false },
  { value: "í", needsFont: false },
  { value: "ǐ", needsFont: false },
  { value: "ì", needsFont: false },
  { value: "ō", needsFont: false },
  { value: "ó", needsFont: false },
  { value: "ǒ", needsFont: false },
  { value: "ò", needsFont: false },
  { value: "ū", needsFont: false },
  { value: "ú", needsFont: false },
  { value: "ǔ", needsFont: false },
  { value: "ù", needsFont: false },
  { value: "ǚ", needsFont: false },
  { value: "「", needsFont: false },
  { value: "」", needsFont: false },
  { value: "（", needsFont: false },
  { value: "）", needsFont: false },
  { value: "", needsFont: true },
];
